/**
 * Wisdom Packet type definitions
 * 
 * Represents synthesized wisdom and insights generated by the system
 */

import { AnyBimbaNode } from './BimbaNode';

export interface WisdomPacket {
  id: string;
  title: string;
  content: string;
  summary: string;
  sourceNodes: AnyBimbaNode[];
  insights: Insight[];
  connections: WisdomConnection[];
  metadata: WisdomMetadata;
  createdAt: string;
  updatedAt: string;
}

export interface Insight {
  id: string;
  type: 'pattern' | 'connection' | 'synthesis' | 'emergence';
  content: string;
  confidence: number; // 0-1
  sourceCoordinates: string[];
  tags?: string[];
}

export interface WisdomConnection {
  fromCoordinate: string;
  toCoordinate: string;
  connectionType: string;
  strength: number; // 0-1
  description: string;
  discoveredBy: 'user' | 'ai' | 'system';
}

export interface WisdomMetadata {
  generatedBy: string; // persona or user ID
  processingTime: number; // milliseconds
  complexity: 'simple' | 'moderate' | 'complex' | 'profound';
  domains: string[]; // subject areas covered
  quality: {
    coherence: number; // 0-1
    novelty: number; // 0-1
    relevance: number; // 0-1
    depth: number; // 0-1
  };
  version: string;
}

// Query and search types
export interface WisdomQuery {
  query: string;
  filters?: {
    domains?: string[];
    complexity?: WisdomMetadata['complexity'][];
    dateRange?: {
      start: string;
      end: string;
    };
    minQuality?: number;
  };
  limit?: number;
  offset?: number;
}

export interface WisdomSearchResult {
  packets: WisdomPacket[];
  totalCount: number;
  facets?: {
    domains: { name: string; count: number }[];
    complexity: { level: string; count: number }[];
  };
  searchTime: number;
}
